-- Demo video script for PolicyPulse Snowflake Lab

USE ROLE TRAINING_ROLE;
USE WAREHOUSE LAB_5_PIPELINE;
USE DATABASE POLICYPULSE_DB;
USE SCHEMA PUBLIC;

-- Show session context
SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

-- Verify objects exist
SHOW TABLES LIKE 'BILLS' IN SCHEMA PUBLIC;
SHOW VIEWS LIKE 'BILLS_ANALYTICS' IN SCHEMA PUBLIC;

-- Prove data is loaded
SELECT COUNT(*) AS bills_row_count
FROM POLICYPULSE_DB.PUBLIC.BILLS;

SELECT *
FROM POLICYPULSE_DB.PUBLIC.BILLS
LIMIT 10;

-- Create/replace analytics view (transformation layer)
CREATE OR REPLACE VIEW POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS AS
SELECT
    BILL_ID,
    SESSION_ID,
    BILL_NUMBER,
    STATUS,
    STATUS_DESC,
    STATUS_DATE,
    YEAR(STATUS_DATE) AS YEAR,
    COMMITTEE_ID,
    TITLE,
    DESCRIPTION
FROM POLICYPULSE_DB.PUBLIC.BILLS
WHERE STATUS_DATE IS NOT NULL;

-- Prove view works
SELECT COUNT(*) AS bills_analytics_rows
FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS;

SELECT *
FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS
LIMIT 10;

-- Query A: Bills by status (aggregation)
SELECT
    STATUS_DESC,
    COUNT(*) AS total_bills
FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS
GROUP BY STATUS_DESC
ORDER BY total_bills DESC;

-- Query B: Bills over time (time-based)
SELECT
    YEAR,
    COUNT(*) AS total_bills
FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS
GROUP BY YEAR
ORDER BY YEAR;

-- Query C: Top committees (aggregation + filter)
SELECT
    COMMITTEE_ID,
    COUNT(*) AS total_bills
FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS
WHERE COMMITTEE_ID IS NOT NULL
GROUP BY COMMITTEE_ID
ORDER BY total_bills DESC
LIMIT 10;

-- Optional (only if your stage exists and you want to show it)
-- LIST @RAW_DOCS;
