-- PolicyPulse Snowflake Schema
-- Creates the BILLS table and BILLS_ANALYTICS view in POLICYPULSE_DB

USE ROLE TRAINING_ROLE;
USE WAREHOUSE LAB_5_PIPELINE;
USE DATABASE POLICYPULSE_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS POLICYPULSE_DB.PUBLIC.BILLS (
    BILL_ID         NUMBER          NOT NULL,
    SESSION_ID      NUMBER,
    BILL_NUMBER     VARCHAR(50),
    STATUS          NUMBER,
    STATUS_DESC     VARCHAR(100),
    STATUS_DATE     DATE,
    TITLE           VARCHAR(2000),
    DESCRIPTION     TEXT,
    COMMITTEE       VARCHAR(500),
    COMMITTEE_ID    NUMBER,
    LAST_ACTION     VARCHAR(2000),
    LAST_ACTION_DATE DATE,
    URL             VARCHAR(1000),
    STATE_LINK      VARCHAR(1000),
    CHANGE_HASH     VARCHAR(64),
    PRIMARY KEY (BILL_ID)
);

CREATE OR REPLACE VIEW POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS AS
SELECT
    BILL_ID,
    SESSION_ID,
    BILL_NUMBER,
    STATUS,
    STATUS_DESC,
    STATUS_DATE,
    YEAR(STATUS_DATE)    AS YEAR,
    COMMITTEE_ID,
    COMMITTEE            AS PRIMARY_COMMITTEE_NAME,
    TITLE,
    DESCRIPTION
FROM POLICYPULSE_DB.PUBLIC.BILLS
WHERE STATUS_DATE IS NOT NULL;

-- Verify
SELECT COUNT(*) AS total_bills FROM POLICYPULSE_DB.PUBLIC.BILLS;
SELECT COUNT(*) AS analytics_rows FROM POLICYPULSE_DB.PUBLIC.BILLS_ANALYTICS;
