from typing import Any, List, Dict
import copy

def openai_tools_to_gemini(tools: List[Dict[str, Any]]) -> Any:
    """
    Transforms OpenAI-style function calling schemas into Gemini FunctionDeclarations.
    
    Args:
        tools (List[Dict[str, Any]]): A list of OpenAI-style tool schema dictionaries.
    
    Returns:
        Any: A structure acceptable to Gemini's GenerativeModel `tools` argument,
             typically a list of Dicts matching Google's expected format, or 
             native genai.types.Tool objects if constructed directly. 
             If generation fails due to SDK mismatch, it returns None.
    """
    try:
        from google.generativeai.types import content_types
        import google.ai.generativelanguage as glm
        
        gemini_tools = []
        for tool in tools:
            if tool.get("type") != "function":
                continue
                
            fn = tool.get("function", {})
            
            # OpenAI Parameter schema is usually a jsonschema object
            params = fn.get("parameters", {})
            properties = params.get("properties", {})
            required = params.get("required", [])
            
            # Map OpenAI types to OpenAPI types expected by Gemini
            # Usually: string, integer, boolean, etc.
            gemini_properties = {}
            for prop_name, prop_data in properties.items():
                prop_type = prop_data.get("type", "string").upper()
                if prop_type == "INT": 
                    prop_type = "INTEGER"
                elif prop_type == "BOOL":
                    prop_type = "BOOLEAN"
                    
                gemini_properties[prop_name] = glm.Schema(
                    type=getattr(glm.Type, prop_type, glm.Type.STRING),
                    description=prop_data.get("description", "")
                )
                
            # Create the function declaration
            func_decl = glm.FunctionDeclaration(
                name=fn.get("name", ""),
                description=fn.get("description", ""),
                parameters=glm.Schema(
                    type=glm.Type.OBJECT,
                    properties=gemini_properties,
                    required=required
                )
            )
            gemini_tools.append(func_decl)
            
        # Wrap the function declarations in a Tool
        return glm.Tool(function_declarations=gemini_tools)
        
    except ImportError:
        # Expected if Gemini is optional and dependency is not installed.
        pass
    except Exception as e:
        # Only log actual runtime errors that aren't missing dependencies
        print(f"Informational Note: Gemini/Agent mode requires extra optional dependencies and API key. reproduce.sh and smoke tests run without them. (Original error: {e})")
        return None

def extract_tool_calls(gemini_response: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Extracts standardized tool calls from the chat response dictionary generated by llm_client.py
    
    Args:
        gemini_response (Dict[str, Any]): The response from llm_client.chat()
        
    Returns:
        List[Dict[str, Any]]: Standardized list of tool calls like [{"name": "...", "arguments": {...}}]
    """
    # Simply extract the tool_calls key which we already normalized in llm_client
    return gemini_response.get("tool_calls", []) or []
